# spring:
#   main:
#     banner-mode: 'off'
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     username: root
#     password: root
#   jpa:
#     database-platform: org.hibernate.dialect.MySQL8Dialect
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#     hibernate:
#       ddl-auto: update
spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: ture
        # use_sql_comments: true  # Adds comments to the generated SQL for better readability
    hibernate:
      ddl-auto: update
      # naming:  # naver use this like this is crearing not auto name like planId = plan_id but this will create error
      #   physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Use standard naming strategy
  # logging:  # after this last three lines we will try when we do the log files in the spring boot
  #   level:
  #     org.hibernate.SQL: DEBUG  # Log the SQL statements
  #     org.hibernate.type.descriptor.sql.BasicTypeRegistry: TRACE  # Log the binding of parameters
